### ISSUE TITLE
support for a website | Google Photos

### ISSUE THREAD

**Issue by lhr88** [Owyn/HandyImage#466]
**Example links to pages with a single image to fullsize: **

- https://photos.app.goo.gl/mnr23FrSEY2tT5m2A

It would be great if Google Photos could be added to HandyImage. A lot of full albums are shared on Google Photos and it would be great, if opening a specific photo would lead to the image being open, rather than the standard Google Photos interface.

Many thanks - you are absolutely amazing!

**Comment by Owyn** [comment]
But then gallery viewing with left \ right keys would stop working, along with all other useful functions of google photos
If you want to quickly download those images there's a hotkey for that in google photos (shift + D)

Adding it would bring more disadvantage than advantage to users in my opinion since google photos is an album image hoster and not just a single image hoster
