### ISSUE TITLE
[bug] fastpic.org

### ISSUE THREAD

**Issue by LeCommonMan** [Owyn/HandyImage#497]
with last two updates fastpic.org was hit or miss, and with the latest 2022.10.25 update it completely broken.
browser: chrome and brave,
OS: mac. 

a typical URL of image :- https://fastpic.org/view/92/2019/1019/3c08433af555c0ece1326534dd07ef69.jpg.html
If we right click & say open image in new tab, then handyimage is triggred and i can see the BG of image changed to my defined white background. 

expectation: that about url ridirect to .jpg file in something line this syntax - https://i91.fastpic.org/big/2020/1010/12/246b8e3f5ed355da98d99b4c5f89bf22.jpg

**Comment by Owyn** [comment]
If you click usermanager icon to see list of ran scripts - are there menu items there? e.g. "configuration" for Handy Image?  
![image](https://user-images.githubusercontent.com/1309656/198291594-99952d63-264b-4304-942e-8c818fc390d6.png)

if not, it's a problem of the userscript manager I reported here: https://github.com/Tampermonkey/tampermonkey/issues/1634

Same issue in my Firefox & Chrome on windows 10.

Script can't do anything there to fix it since the script doesn't even get to run

**Comment by LeCommonMan** [comment]
> are there menu items there? e.g. "configuration" for Handy Image?
You are correct, indeed that menu is missing in brave and chrome. 
https://i120.fastpic.org/big/2022/1027/13/d39c202c341ab4841d4346a6d05c6613.jpg

where as in firefox - i can see that configuration menu item in one image.
https://fastpic.org/view/120/2022/1027/_d528b93b15906dff6bac64c972b9b7e4.jpeg.html

**Comment by Owyn** [comment]
> You are correct, indeed that menu is missing in brave and chrome.

That means it's a problem of the script manager extension and my script doesn't run at all - so I can't really do anything here :-(

**Comment by LeCommonMan** [comment]
updated my previous comment with aditional info.
is it sems to TM's malfunctioning, cant even use shortcut like, Q to resize imaged in brave. where as its work fine in FF.

**Comment by zubrRB** [comment]
The script works without problems in AdGuard + Chrome.

**Comment by Owyn** [comment]
Disable Adblock (uBlock) for that site, it should help.

**Comment by Owyn** [comment]
Now Should work even without disabling adblock I think
