### ISSUE TITLE
[REQUEST] Add support for sex.com

### ISSUE THREAD

**Issue by masterofobzene** [Owyn/HandyImage#511]
**Example links to pages with a single image to fullsize: **
[NSFW LINK](https://porngifs.xxx/big-ass-blonde-dressed-as-a-horny-nun-ready-to-sin-with-your-big-cock/)
-

**Comment by Owyn** [comment]
Way too generic of a website any redeeming features and overall low user experience (slow white website with just CEO wordlist spam), not even sure than more than few ppl use that site or if there could be viruses if I turn off my adblock 🤷🏻‍♀️  

I'd just suggest using a more popular alternative

I don't want to add it since it's neither an image host ppl can upload to nor it seems anyhow popular.
