### ISSUE TITLE
Direct link of image.

### ISSUE THREAD

**Issue by junomarian** [Owyn/HandyImage#528]
If script is on, how to let Downloadthemall get direct link images? but Downloadthemall not gets direct links of images.

**Comment by Owyn** [comment]
Click media tab instead of Links in downloadthemall:
![image](https://user-images.githubusercontent.com/1309656/228258915-3f2618fc-fed9-4165-8c71-fd1441bcc945.png)

or if you don't want to actually view images with all the features of the script - you can enable option of "direct links" in Handy's configuration so it'd simply redirect to images right away instead of showing them

**Comment by junomarian** [comment]
> Click media tab instead of Links in downloadthemall: ![image](https://user-images.githubusercontent.com/1309656/228258915-3f2618fc-fed9-4165-8c71-fd1441bcc945.png)
> 
> or if you don't want to actually view images with all the features of the script - you can enable option of "direct links" in Handy's configuration so it'd simply redirect to images right away instead of showing them

where is this configuration settings?
